# Reference https://github.com/JeffreyCA/spleeter-web
# Spleeter-Web (GPU)
# Combines logic from docker-compose.gpu.yml, docker-compose.prod.selfhost.yml, docker-compose.prod.yml
#
# Improvements to settings.py & settings_docker.py that can allow for environment variables to be used with compose
#
# MEDIA_ROOT = os.getenv('MEDIA_ROOT', 'media')
# MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
# SEPARATE_DIR = os.getenv('SEPARATE_DIR', 'separate')
# UPLOAD_DIR = os.getenv('UPLOAD_DIR', 'uploads')
#
# Action items
# CPU Pinning / UID / GID / GIDLIST? / UMASK? / SLAVE:RW for unassigned drives? / APP_HOST, stop using wildcard /
#
# Current State:  
#   Dynamic Mixes do not playback; 
#   Stems created with Dynamic Mix do not download (e.g. nginx port missing in url)
#   Custom Nginx.conf required

version: '3.4'
x-celery-env: &celery-env
  - DJANGO_SETTINGS_MODULE=django_react.settings_docker
  - CELERY_BROKER_URL=redis://redis:6379/0
  - CELERY_RESULT_BACKEND=redis://redis:6379/0
  - CPU_SEPARATION=0
  - CELERY_FAST_QUEUE_CONCURRENCY=${CELERY_FAST_QUEUE_CONCURRENCY:-3}
  - CELERY_SLOW_QUEUE_CONCURRENCY=${CELERY_SLOW_QUEUE_CONCURRENCY:-1}
  - NVIDIA_VISIBLE_DEVICES=<Unraid GPU-GUID or all>
  - NVIDIA_DRIVER_CAPABILITIES=all
  - DEFAULT_FILE_STORAGE=FILE
  #- NGINX_PORT=3148
  - MEDIA_ROOT=media
  - MEDIA_URL=/media/
  - SEPARATE_DIR=separate
  - UPLOAD_DIR=uploads
  
services:
  redis:
    image: redis:6.0-buster
    hostname: redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    #custom Unraid network name
    networks:
      - dockernet
    restart: always
  nginx:
    image: jeffreyca/spleeter-web-nginx:${TAG:-latest}
    #syntax for pulling previous versions
    #image: jeffreyca/spleeter-web-nginx:v3.9.0
    ports:
      - "<custom port for Unraid>:80"
    environment:
      - NGINX_PORT=3148
    volumes:
      - staticfiles:/webapp/staticfiles
      #added volumes for self hosting & unraid shares
      - /mnt/user/unraid/paths:/webapp/media
    #custom Unraid network name
    networks:
      - dockernet
    depends_on:
      - api
    restart: always
  api:
    image: jeffreyca/spleeter-web-backend:${TAG:-latest}-gpu
    #syntax for pulling previous versions
    #image: jeffreyca/spleeter-web-backend:v3.9.0-gpu
    volumes:
      - assets:/webapp/frontend/assets
      - sqlite-data:/webapp/sqlite
      - staticfiles:/webapp/staticfiles
      #added volumes for self hosting & unraid shares
      - /mnt/user/unraid/paths:/webapp/media
    #custom Unraid network name
    networks:
      - dockernet
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=django_react.settings_docker
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CPU_SEPARATION=0
      #unraid host ip / name required?  May need to figure 
      - APP_HOST=*
      #required?
      - YOUTUBE_API_KEY=<INSERT YT KEY HERE>
       #- NGINX_PORT=3148
      - DEFAULT_FILE_STORAGE=FILE
      - MEDIA_ROOT=media
      - SEPARATE_DIR=separate
      - UPLOAD_DIR=uploads
    depends_on:
      - redis
      - frontend
    restart: always
  celery-fast:
    image: jeffreyca/spleeter-web-backend:${TAG:-latest}-gpu
    #syntax for pulling previous versions
    #image: jeffreyca/spleeter-web-backend:v3.9.0-gpu
    entrypoint: ./celery-fast-entrypoint.sh
    volumes:
      - celery-data:/webapp/celery
      - pretrained-models:/webapp/pretrained_models
      - sqlite-data:/webapp/sqlite
      #added volumes for self hosting & unraid shares
      - /mnt/user/unraid/paths:/webapp/media
    #custom Unraid network name
    networks:
      - dockernet
    runtime: nvidia
    environment: *celery-env
    depends_on:
      - redis
    restart: always
  celery-slow:
    image: jeffreyca/spleeter-web-backend:${TAG:-latest}-gpu
    #syntax for pulling previous versions
    #image: jeffreyca/spleeter-web-backend:v3.9.0-gpu
    entrypoint: ./celery-slow-entrypoint.sh
    volumes:
      - celery-data:/webapp/celery
      - pretrained-models:/webapp/pretrained_models
      - sqlite-data:/webapp/sqlite
      #added volumes for self hosting & unraid shares
      - /mnt/user/unraid/paths:/webapp/media
    #custom Unraid network name
    networks:
      - dockernet
    runtime: nvidia
    environment: *celery-env
    depends_on:
      - redis
    restart: always
  frontend:
    image: jeffreyca/spleeter-web-frontend:${TAG:-latest}
    #syntax for pulling previous versions
    #image: jeffreyca/spleeter-web-frontend:v3.9.0
    volumes:
      - assets:/webapp/frontend/assets
    #custom Unraid network name
    networks:
      - dockernet
    stdin_open: true
    tty: true
    # Is this config intentional? Typo? Should it be always?
    restart: "no"
volumes:
  assets:
  celery-data:
  pretrained-models:
  redis-data:
  sqlite-data:
  staticfiles:
#custom Unraid network name
networks:
  dockernet:
    external: true
